### ISSUE TITLE
D1Database' object has no attribute 'rowcount'

### ISSUE THREAD

**Issue by aliahadmd** [G4brym/django-d1#1]
Hi, 
Thank you so much to create this. I have an issue. I just create new django project to test this library. as usual i did `python manage.py migrate` and then `python manage.py createsuperuser` .  Everything is okay but little bit slow. However, when I am going to login admin dashboard I am getting this error, 

`AttributeError: 'D1Database' object has no attribute 'rowcount'
[25/May/2024 00:30:50] "POST /admin/login/?next=/admin/ HTTP/1.1" 500 191037`

![image](https://github.com/G4brym/django-d1/assets/90032081/7b39a061-56df-44f7-98c0-010cf85eb2c3)

**Comment by G4brym** [comment]
Hey @aliahadmd this issue is fixed in version 0.0.6, can you try updating to see if it solved?
Yeah everything is quite slow, i'm still looking into ways to speed up the queries, but since every query is executed in individual http requests, a lot of time is lost in handshakes and connecting to the server
