### ISSUE TITLE
Error with 'true' and True

### ISSUE THREAD

**Issue by dsin** [G4brym/django-d1#2]
Problem when access /admin/auth/user/
Error: 
`File "/usr/local/lib/python3.10/site-packages/django/contrib/admin/templatetags/admin_list.py", line 182, in _boolean_icon
    "admin/img/icon-%s.svg" % {True: "yes", False: "no", None: "unknown"}[field_val]
KeyError: 'true'`

Same problem occurs on /admin/password_change/
ValidationError at /admin/password_change/ `['“true” value must be either True or False.']`

**Comment by G4brym** [comment]
Hey @dsin thanks for reporting this, i've fixed the issue on the latest (v0.0.7) version.
I recommend you start a database from scratch with the new version, otherwise you will need to go on to your D1 database and update all boolean fields to be small ints.
For example in that change password case, you need to open your `auth_user` table and update the fields `is_superuser`, `is_staff` and `is_active` to be either 1 or 0.
Let me know if the new version fixes your issue.
